name: GitHub Shawzin Secrets

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.BUG_REPORT_TO }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.BUG_REPORT_TO}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          BUG_REPORT_TOKEN: ${{ secrets.BUG_REPORT_TO }}
        if:  env.BUG_REPORT_TOKEN == '5794288074:AAEi6L7a9EbbGhEK46FRG9FyyhwQ6oove_I'
        run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          BUG_REPORT_TOKEN: ${{ secrets.BUG_REPORT_TO }}
        if:  env.BUG_REPORT_TOKEN != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
